<?php
$this->load->view('admins/layouts/header'); $this->load->view('admins/layouts/sidebar');
$types=array('rating'=>'คะแนน 1–5','single_choice'=>'เลือกคำตอบเดียว','multiple_choice'=>'เลือกได้หลายคำตอบ','short_text'=>'ข้อความสั้น','long_text'=>'ข้อเสนอแนะแบบยาว');
?>
<div class="admin-content"><header class="admin-topbar px-3 px-lg-4 py-3 border-bottom"><h1 class="h4 mb-1"><?= html_escape($survey->title) ?></h1><p class="mb-0 text-secondary">จัดการคำถามและลำดับ</p></header><main class="admin-main py-4">
<?php foreach(array('success'=>'success','error'=>'danger') as $key=>$class): if($this->session->flashdata($key)): ?><div class="alert alert-<?= $class ?>"><?= html_escape($this->session->flashdata($key)) ?></div><?php endif; endforeach; ?>
<div class="d-flex gap-2 mb-3"><a class="btn btn-outline-secondary" href="<?= site_url('admin/surveys') ?>">กลับ</a><a class="btn btn-success" href="<?= site_url('admin/surveys/assign/'.$survey->id) ?>">เปิดใช้กับรุ่นอบรม</a></div>
<?php if($locked): ?><div class="alert alert-warning">แบบประเมินนี้มีผู้ตอบแล้ว โครงสร้างคำถามถูกล็อก หากต้องการเปลี่ยนคำถามให้สร้างชุดใหม่</div><?php endif; ?>
<div class="row g-4"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">เพิ่มคำถาม</h2><form method="post" action="<?= site_url('admin/surveys/questions/'.$survey->id.'/add') ?>"><label class="form-label mt-2">คำถาม *</label><textarea class="form-control" name="question_text" required></textarea><label class="form-label mt-3">ประเภท</label><select class="form-select" name="question_type" id="question_type"><?php foreach($types as $v=>$label): ?><option value="<?= $v ?>"><?= $label ?></option><?php endforeach; ?></select><div id="option_box"><label class="form-label mt-3">ตัวเลือก (หนึ่งบรรทัดต่อหนึ่งข้อ)</label><textarea class="form-control" name="options" rows="5"></textarea></div><label class="form-check mt-3"><input class="form-check-input" type="checkbox" name="is_required" value="1"><span class="form-check-label">คำถามบังคับ</span></label><button class="btn btn-primary w-100 mt-3" <?= $locked?'disabled':'' ?>>เพิ่มคำถาม</button></form></div></div></div>
<div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">คำถาม <?= count($questions) ?> ข้อ</h2><?php foreach($questions as $i=>$q): ?><div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between gap-3"><div><strong><?= ($i+1).'. '.html_escape($q->question_text) ?></strong><div class="small text-secondary"><?= $types[$q->question_type] ?><?= $q->is_required?' · บังคับ':'' ?></div><?php if($q->options): ?><ul class="mb-0 mt-2"><?php foreach($q->options as $o): ?><li><?= html_escape($o->option_text) ?></li><?php endforeach; ?></ul><?php endif; ?></div><div class="text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="<?= site_url('admin/surveys/questions/'.$survey->id.'/move/'.$q->id.'/up') ?>">↑</a> <a class="btn btn-sm btn-outline-secondary" href="<?= site_url('admin/surveys/questions/'.$survey->id.'/move/'.$q->id.'/down') ?>">↓</a> <a class="btn btn-sm btn-outline-danger" href="<?= site_url('admin/surveys/questions/'.$survey->id.'/delete/'.$q->id) ?>" onclick="return confirm('ลบคำถามนี้หรือไม่?')">ลบ</a></div></div></div><?php endforeach; ?><?php if(!$questions): ?><p class="text-secondary">ยังไม่มีคำถาม</p><?php endif; ?></div></div></div></div>
<script>var t=document.getElementById('question_type'),b=document.getElementById('option_box');function toggle(){b.style.display=(t.value==='single_choice'||t.value==='multiple_choice')?'block':'none'}t.addEventListener('change',toggle);toggle();</script>
</main><?php $this->load->view('admins/layouts/footer'); ?>
