<?php $this->load->view('admins/layouts/header'); $this->load->view('admins/layouts/sidebar'); $url=site_url('evaluation/'.$assignment->public_code); $eligible=$stats?(int)$stats->eligible_count:0; $done=$stats?(int)$stats->completed_count:0; ?>
<style>@media print{.admin-sidebar,.admin-topbar,.no-print,.admin-footer{display:none!important}.admin-content{margin:0!important}.qr-sheet{box-shadow:none!important;text-align:center;padding-top:15vh!important}}</style>
<div class="admin-content"><header class="admin-topbar px-3 px-lg-4 py-3 border-bottom"><h1 class="h4 mb-1">QR Code แบบประเมิน</h1><p class="mb-0 text-secondary"><?= html_escape($assignment->course_title) ?> / <?= html_escape($assignment->batch_no) ?></p></header><main class="admin-main py-4">
<?php if($this->session->flashdata('success')): ?><div class="alert alert-success no-print"><?= html_escape($this->session->flashdata('success')) ?></div><?php endif; ?>
<div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm qr-sheet"><div class="card-body text-center p-5"><h2><?= html_escape($assignment->survey_title) ?></h2><p><?= html_escape($assignment->course_title) ?> · <?= html_escape($assignment->batch_no) ?></p><div id="qr" class="d-flex justify-content-center" aria-label="QR Code"></div><p class="small text-break mt-3"><?= html_escape($url) ?></p><button class="btn btn-primary no-print" id="download">ดาวน์โหลด PNG</button> <button class="btn btn-outline-secondary no-print" onclick="window.print()">พิมพ์ A4</button></div></div></div>
<div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">สถานะ</h2><div class="display-6"><?= $done ?> / <?= $eligible ?></div><p>ตอบแล้ว <?= $eligible?number_format($done*100/$eligible,1):0 ?>%</p><p><strong>เปิด:</strong> <?= html_escape($assignment->open_at) ?><br><strong>ปิด:</strong> <?= html_escape($assignment->close_at) ?></p><div class="d-grid gap-2 no-print"><a class="btn btn-success" href="<?= site_url('admin/surveys/report/'.$assignment->id) ?>">ดูรายงาน</a><a class="btn btn-outline-primary" href="<?= site_url('admin/surveys/export/'.$assignment->id) ?>">ส่งออก CSV</a><a class="btn btn-outline-warning" href="<?= site_url('admin/surveys/assignment/'.$assignment->id.'/regenerate') ?>" onclick="return confirm('QR เดิมจะใช้งานไม่ได้ ต้องการสร้างใหม่หรือไม่?')">สร้าง QR ใหม่</a><a class="btn btn-outline-danger" href="<?= site_url('admin/surveys/assignment/'.$assignment->id.'/close') ?>" onclick="return confirm('ปิดรับคำตอบหรือไม่?')">ปิดรับคำตอบ</a></div></div></div></div></div>
<div class="card border-0 shadow-sm mt-4 no-print"><div class="card-body"><h2 class="h5">รายชื่อผู้มีสิทธิ์</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>ตรวจข้อมูล</th><th>แบบประเมิน</th></tr></thead><tbody><?php foreach($roster as $person): ?><tr><td><?= html_escape($person->first_name.' '.$person->last_name) ?></td><td><?= html_escape($person->email) ?></td><td><?= $person->profile_confirmed_at?'<span class="badge text-bg-success">ยืนยันแล้ว</span>':'<span class="badge text-bg-secondary">ยังไม่ยืนยัน</span>' ?></td><td><?= $person->completed_at?'<span class="badge text-bg-success">ตอบแล้ว</span>':'<span class="badge text-bg-warning">ยังไม่ตอบ</span>' ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<script src="<?= base_url('assets/js/qrcode.min.js') ?>"></script><script>var url=<?= json_encode($url) ?>,box=document.getElementById('qr');if(window.QRCode){new QRCode(box,{text:url,width:300,height:300,correctLevel:QRCode.CorrectLevel.H});}document.getElementById('download').onclick=function(){var img=box.querySelector('img'),canvas=box.querySelector('canvas'),a=document.createElement('a');a.download='survey-qr-<?= (int)$assignment->id ?>.png';a.href=img&&img.src?img.src:canvas.toDataURL('image/png');a.click()};</script>
</main><?php $this->load->view('admins/layouts/footer'); ?>
